In [2]:
import pandas as pd
import numpy as np
import yfinance as yf
import plotly.offline as plo
import datetime as dt

In [3]:
plo.init_notebook_mode(connected=True)
pd.options.plotting.backend = 'plotly'

In [4]:
endDate = dt.datetime.today()
startDate = dt.datetime(2012,1,1)
df = yf.download('HDFCBANK.NS',end=endDate,start=startDate)

[*********************100%***********************]  1 of 1 completed

In [5]:
df.head()

Price            Close        High         Low        Open      Volume
Ticker     HDFCBANK.NS HDFCBANK.NS HDFCBANK.NS HDFCBANK.NS HDFCBANK.NS
Date
2012-01-02   95.029961   95.686717   93.393623   95.486351     7029996
2012-01-03   97.768311   98.157914   95.731240   96.042922     6878476
2012-01-04   98.692238   99.059584   95.920488   98.380556     9742956
2012-01-05   98.770149   99.449177   98.024335   98.848071     6761212
2012-01-06  100.918541  101.775671   97.723794   98.180185     7954444

In [6]:

close = df.Close

In [7]:
close.head()

Ticker      HDFCBANK.NS
Date
2012-01-02    95.029961
2012-01-03    97.768311
2012-01-04    98.692238
2012-01-05    98.770149
2012-01-06   100.918541

In [8]:
close.plot()

In [9]:
close.columns = ['Close']

In [10]:
close['Log_ret'] = np.log(close['Close']/close['Close'].shift(1))

C:\Users\shaba\AppData\Local\Temp\ipykernel_2104\1709329719.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
close.dropna(inplace=True)
close.head()

C:\Users\shaba\AppData\Local\Temp\ipykernel_2104\3367665841.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                 Close   Log_ret
Date
2012-01-03   97.768311  0.028408
2012-01-04   98.692238  0.009406
2012-01-05   98.770149  0.000789
2012-01-06  100.918541  0.021518
2012-01-09  101.452866  0.005281

In [12]:
close['Log_ret'].plot()

In [13]:
close['Log_sum'] = close['Log_ret'].cumsum()

C:\Users\shaba\AppData\Local\Temp\ipykernel_2104\3253131132.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [14]:
close['Log_sum'].plot()

In [15]:
closeMean = close['Close'].mean()

In [16]:
close['Mean_sub'] = close['Close'] - closeMean
close['Sub_sq'] = np.square(close['Mean_sub'])

C:\Users\shaba\AppData\Local\Temp\ipykernel_2104\2034135929.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\shaba\AppData\Local\Temp\ipykernel_2104\2034135929.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [17]:
subSum = close['Sub_sq'].sum()
volatility = (subSum/close.shape[0])**0.5
volatility

np.float64(266.8153001929622)

In [18]:
close.head()

                 Close   Log_ret   Log_sum    Mean_sub         Sub_sq
Date
2012-01-03   97.768311  0.028408  0.028408 -399.323077  159458.920087
2012-01-04   98.692238  0.009406  0.037814 -398.399150  158721.882737
2012-01-05   98.770149  0.000789  0.038603 -398.321239  158659.809155
2012-01-06  100.918541  0.021518  0.060121 -396.172847  156952.924637
2012-01-09  101.452866  0.005281  0.065402 -395.638522  156529.840307

In [19]:
close['Rolling_mean'] = close['Close'].rolling(14).mean()

C:\Users\shaba\AppData\Local\Temp\ipykernel_2104\3576997028.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [20]:
close['Rolling_sub'] = close['Close'] - close['Rolling_mean']
close['Rolling_sq'] = np.square(close['Rolling_sub'])

C:\Users\shaba\AppData\Local\Temp\ipykernel_2104\1199564029.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\shaba\AppData\Local\Temp\ipykernel_2104\1199564029.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [21]:
close['Volatility'] = (close['Rolling_sq'].rolling(14).sum()/14)**0.5

C:\Users\shaba\AppData\Local\Temp\ipykernel_2104\3755637557.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
close['Volatility'].dropna().plot()

In [23]:
df.columns = ['Close','High','Low','Open','Volume']

In [24]:
df.columns

Index(['Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [25]:
df[['Close','High','Low','Open']].plot()

In [26]:
monthly = df.resample('1M').agg({'Open':'last','High':'max','Low':'min','Close':'last'})

C:\Users\shaba\AppData\Local\Temp\ipykernel_2104\1643770087.py:1: FutureWarning:

'M' is deprecated and will be removed in a future version, please use 'ME' instead.

In [27]:
monthly[['Close','High','Low','Open']].plot()

In [28]:
monthly['Log_ret'] = np.log(monthly['Close']/monthly['Close'].shift(-1))
monthly['Log_sum'] = monthly['Log_ret'].cumsum()
monthly['Log_ret'].plot()

In [30]:
monthly['Log_sum'].plot()

In [31]:
close.head()

,Close,Log_ret,Log_sum,Mean_sub,Sub_sq,Rolling_mean,Rolling_sub,Rolling_sq,Volatility
Date,,,,,,,,,
2012-01-03,97.768311,0.028408,0.028408,-399.323077,159458.920087,NaN,NaN,NaN,NaN
2012-01-04,98.692238,0.009406,0.037814,-398.399150,158721.882737,NaN,NaN,NaN,NaN
2012-01-05,98.770149,0.000789,0.038603,-398.321239,158659.809155,NaN,NaN,NaN,NaN
2012-01-06,100.918541,0.021518,0.060121,-396.172847,156952.924637,NaN,NaN,NaN,NaN
2012-01-09,101.452866,0.005281,0.065402,-395.638522,156529.840307,NaN,NaN,NaN,NaN

In [32]:
close['Avg'] = close['Close'].rolling(50).mean()

C:\Users\shaba\AppData\Local\Temp\ipykernel_2104\2374133269.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [33]:
close[['Avg','Close']].plot()